### ISSUE TITLE
Missing parcel in Schaefer 1000 conte69

### ISSUE THREAD

**Issue by royj23** [ThomasYeoLab/CBIG#10]
Hello! First, thanks for providing this great resource. 

Our group is using different versions/resolutions of the Schaefer parcellations, and we noticed that the 1000-node parcellation cifti files seem to be missing a parcel in the right hemisphere. We are using: 
- 'Schaefer2018_1000Parcels_7Networks_order.dlabel.nii': no label 533
- 'Schaefer2018_1000Parcels_17Networks_order.dlabel.nii' no label 555
As a result, we find 501 unique labels in the left hemisphere, and only 500 unique labels in the right hemisphere.

All labels seem to be present in the fsaverage5 annotation labels however, with the same number of unique labels in each hemisphere. 

Many thanks for your help!

**Comment by rubykong** [comment]
@royj23 Actually there should be two parcels missing, one is 533, the other is 903. 
The root cause is that the parcellations were created in fsaverage6 space, and for the 1000-ROI parcellation we have this issue in the fslr32k projection that: parcel 533 is missing due to projection and parcel 903 is missing due to the discrepancies in the medial wall area. To make our parcellations consistent across different spaces (MNI, fsaverage, fsLR), we don't want to manually change the order of the parcellation labels. 
I thought I have mentioned it somewhere in the readme but clearly I also couldn't find it... Thanks for approaching us! We will modify the readme to reflect this issue.

**Comment by royj23** [comment]
Hi @rubykong , thanks for your quick and informative reply! We'll make note of this on our end :)
