### ISSUE TITLE
parcelation in MNI space 

### ISSUE THREAD

**Issue by ssalzgeber** [ThomasYeoLab/CBIG#23]
Hello, 

We have a question that might have a very easy answer, but we are not able to solve it. 

We are working on a project where we want to obtain time series from functional MRI images (volumetric space) using the Schaefer 400 parcel, 17 network atlas. However, the available atlases differ from our images in terms of voxel size (1 and 2mm vs 3mm in our images). Our first approach was to resize the atlas using spmcalc, but that changed the values of the atlas making the labels continuous. 

So the question is whether there is a way to obtain the atlas in the right size in volumetric space? Functional data was analysed using spm12.

Many thanks, Sarah

**Comment by rubykong** [comment]
@ssalzgeber I think there are two ways to resolve it. 
1) You can use Ants registration to register the parcellation to other space. To do this, you need to run recon-all on your T1 images. Check here fore more info: https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/registration/Wu2017_RegistrationFusion

2) When you say ” but that changed the values of the atlas making the labels continuous.", is it because you are using linear interpolation? You can check if there is a nearest interpolation.
