### ISSUE TITLE
Incorrect LUT (Yan2023)?

### ISSUE THREAD

**Issue by oliver-xie** [ThomasYeoLab/CBIG#48]
I was trying to get the network assignment from the LUT file. While the readme file of the Yan2023 homotopic parcellation reads, "Parcel 1 correspondes to parcel 201 and so on", the LUT file (400Parcels_Yeo2011_7Networks_LUT.txt) shows:
   1 0.80392 0.24314 0.30588 7networks_LH_Default_FPole_1
   2 0.80392 0.24314 0.30588 7networks_LH_Default_FPole_2
   3 0.80392 0.24314 0.30588 7networks_LH_Default_IPL_1
...
  201 0.80392 0.24314 0.30588 7networks_RH_Default_FPole_1
  202 0.80392 0.24314 0.30588 7networks_RH_Default_IPL_1

Moreover, the network assignment does not seem to match either. For example, there are 48 DMN ROIs on the left (ROI 1-48) and 35 on the right hemisphere (ROI 201-235). Did I miss something here?
Thanks!
Oliver

https://raw.githubusercontent.com/ThomasYeoLab/CBIG/master/stable_projects/brain_parcellation/Yan2023_homotopic/parcellations/MNI/yeo7/fsleyes_lut/400Parcels_Yeo2011_7Networks_LUT.txt

**Comment by Matilda-Yxx** [comment]
Thanks for writing in. Yes, ROI 2 corresponds to ROI 202 despite the "mismatched" network labels. 

A homotopic parcel pair could be assigned to different networks since network distribution is asymmetric across the two hemispheres. You can refer to our paper for more details (fig 7 and Section 3.7).
