### ISSUE TITLE
Potential algorithm implementation error on group parcellation in MS-HBM (a.k.a. Yeo 2011 parcellation method)

### ISSUE THREAD

**Issue by shuqike** [ThomasYeoLab/CBIG#56]
### Expected situation

According to the paper "Clustering on the Unit Hypersphere using von Mises-Fisher Distributions" by Arindam Banerjee et al., the normalizing constant of a von Mises-Fisher distribution is given by

$$ c_d(\kappa)=\frac{\kappa^{d/2-1}}{(2\pi)^{d/2}I_{d/2-1}(\kappa)} $$

where $d$ is the dimension of a feature vector.

### Actual situation

However, in the code [CBIG_VonmisesSeriesClustering_fix_bessel_randnum_bsxfun.m](https://github.com/ThomasYeoLab/CBIG/blob/424e2d9633521b2521d46e4bf22efa74d894f29f/utilities/matlab/DSP/CBIG_VonmisesSeriesClustering_fix_bessel_randnum_bsxfun.m#L4) line [129](https://github.com/ThomasYeoLab/CBIG/blob/424e2d9633521b2521d46e4bf22efa74d894f29f/utilities/matlab/DSP/CBIG_VonmisesSeriesClustering_fix_bessel_randnum_bsxfun.m#L129):
`tic, clustered = direcClus_fix_bessel_bsxfun(series, num_clusters, size(series, 2) - 1, num_tries, lambda, 0, 0, 1e-4, 1, max_iter, 1);`
you passed `size(series, 2) - 1` into the `direcClus_fix_bessel_bsxfun` function. Is this equivalent to $c_{d-1}(\kappa)$?

In this case, should we use `size(series, 2)` without minus 1 instead?

Thanks!

**Comment by rubykong** [comment]
@shuqike you are right that actually no need to -1. This is a very old bug thomas made long time ago and we didn't want to fix. Because this only affects the approximation. I am referring to AppendixB in Lashkari et al., NeuroImage 2010 (Discovering structure in the space of fMRI selectivity profiles). We are using the upper bound as the final approximation. However, using D-1 rather than D still holds the approximation (Equation B.7). It's just that it's no longer the upper bound.
We don't want to fix it because it will affect the replication of some old scripts. And since it doesn't really affect the performance, we decide to keep it to D-1.

**Comment by shuqike** [comment]
I see. Thanks for quick response!
